/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Direct: typeof import('./components/direct.vue')['default']
    Direct_exercise: typeof import('./components/direct_exercise.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    V_bind: typeof import('./components/v_bind.vue')['default']
    V_for: typeof import('./components/v_for.vue')['default']
    V_for_and_on: typeof import('./components/v_for_and_on.vue')['default']
    V_model: typeof import('./components/v_model.vue')['default']
    VFor: typeof import('./components/v-for.vue')['default']
  }
}
