/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CurrentSelect: typeof import('./components/CurrentSelect.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    ExchangeRateResults: typeof import('./components/ExchangeRateResults.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LineChartComponent: typeof import('./components/LineChartComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
