/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/LoggedIn': RouteRecordInfo<'/LoggedIn', '/LoggedIn', Record<never, never>, Record<never, never>>,
    '/Middleware.vue/admin': RouteRecordInfo<'/Middleware.vue/admin', '/Middleware/vue/admin', Record<never, never>, Record<never, never>>,
    '/Middleware.vue/premiumUser': RouteRecordInfo<'/Middleware.vue/premiumUser', '/Middleware/vue/premiumUser', Record<never, never>, Record<never, never>>,
    '/Middleware.vue/regularUser': RouteRecordInfo<'/Middleware.vue/regularUser', '/Middleware/vue/regularUser', Record<never, never>, Record<never, never>>,
    '/SignUp': RouteRecordInfo<'/SignUp', '/SignUp', Record<never, never>, Record<never, never>>,
    '/TryPinia': RouteRecordInfo<'/TryPinia', '/TryPinia', Record<never, never>, Record<never, never>>,
    '/TryPost': RouteRecordInfo<'/TryPost', '/TryPost', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
