/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ArraySyntax: typeof import('./components/arraySyntax.vue')['default']
    ClassStylesBinding: typeof import('./components/class-styles-binding.vue')['default']
    ComPro: typeof import('./components/comPro.vue')['default']
    Exercise1: typeof import('./components/Exercise1.vue')['default']
    Exercise2: typeof import('./components/Exercise2.vue')['default']
    ExerciseTwo: typeof import('./components/ExerciseTwo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    JsArrayFilter: typeof import('./components/jsArrayFilter.vue')['default']
    ResponsiveDesign: typeof import('./components/responsiveDesign.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
