/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CinemaInfo: typeof import('./components/CinemaInfo.vue')['default']
    CinemaLocation: typeof import('./components/CinemaLocation.vue')['default']
    CinemaTicket: typeof import('./components/CinemaTicket.vue')['default']
    DateSelect: typeof import('./components/DateSelect.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    T: typeof import('./components/T.vue')['default']
    TheaterMap: typeof import('./components/TheaterMap.vue')['default']
    TheaterSelect: typeof import('./components/TheaterSelect.vue')['default']
    Theatertry: typeof import('./components/theatertry.vue')['default']
    TimeSelect: typeof import('./components/TimeSelect.vue')['default']
  }
}
