/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Date: typeof import('./components/Date.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheaterCompo: typeof import('./components/TheaterCompo.vue')['default']
    Time: typeof import('./components/Time.vue')['default']
  }
}
